### ISSUE TITLE
Blog: Configurer les URL Redirection

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#103]
voir #71

## TODO
=== blog_posts ===
 - [x] http://staging.antistatique.net/blog/2009/02/27/javascript-non-obstructif/
 - [x] http://staging.antistatique.net/blog/2009/06/23/holy-cow-a-lausannejai-nomme-the-burger-place/
 - [x] http://staging.antistatique.net/blog/2009/07/21/capture-ecran-iphone/
 - [x] http://staging.antistatique.net/blog/2010/02/25/west/
 - [x] http://staging.antistatique.net/blog/2010/05/06/lift10-deuxieme-jour/
 - [x] http://staging.antistatique.net/blog/2011/04/12/tests-utilisateurs/
 - [x] http://staging.antistatique.net/blog/2013/05/31/webmardi-impession-3d/
 - [x] http://staging.antistatique.net/blog/2013/06/18/tests-utilisateur-ce-vendredi-portez-vous-volontaire-et-recevez-50/
 - [x] http://staging.antistatique.net/blog/2013/07/01/les-10-principes-pour-la-creation-de-services-digitaux-dun-gouvernement-selon-gov-uk/
 - [x] http://staging.antistatique.net/blog/2013/08/13/tests-utilisateur-ce-vendredi-30-pour-seulement-20-minutes/
 - [x] http://staging.antistatique.net/blog/2013/08/13/pour-vous-remercier-chf-1000-cash/
 - [x] http://staging.antistatique.net/blog/2013/08/15/bootstrap-devient-beaucoup-plus-accessible/
 - [x] http://staging.antistatique.net/blog/2013/08/16/soutien-electrosanne-via-les-reseaux-sociaux/
 - [x] http://staging.antistatique.net/blog/2013/08/29/antistatique-lance-slidedeck-io-un-annuaire-de-presentations-techniques-en-html/
 - [x] http://staging.antistatique.net/blog/2013/09/17/debugging-with-xdebug-and-phpstorm-on-macos-x/
 - [x] http://staging.antistatique.net/blog/2013/09/18/fe2013-un-designer-doit-savoir-coder/
 - [x] http://staging.antistatique.net/blog/2013/09/23/mais-qui-est-cette-fille/
 - [x] http://staging.antistatique.net/blog/2013/10/16/un-barbu-au-bureau/
 - [x] http://staging.antistatique.net/blog/2013/10/23/conference-softshake-a-geneve-agile-developpement-logiciel-web-et-mobile/
 - [x] http://staging.antistatique.net/blog/2013/11/18/creativemornings-ou-la-bonne-maniere-de-commencer-sa-journee/
 - [x] http://staging.antistatique.net/blog/2013/11/19/tests-utilisateurs-ce-vendredi-recevez-30-pour-20-minutes/
 - [x] http://staging.antistatique.net/blog/2013/12/12/2013-une-conclusion-en-prix-et-en-recompenses/
 - [x] http://staging.antistatique.net/blog/2013/12/16/email-marketing-desormais-gmail-affiche-les-images-par-defaut/
 - [x] http://staging.antistatique.net/blog/2013/12/19/deuxieme-barbu-au-bureau/
 - [x] http://staging.antistatique.net/blog/2014/01/14/les-grandes-retrouvailles/
 - [x] http://staging.antistatique.net/blog/2014/01/08/styleguides-dynamiques-et-les-bonnes-methodes-de-communication-dun-projet-web/
 - [x] http://staging.antistatique.net/blog/2014/01/20/an-italian-joins-the-crew/
 - [x] http://staging.antistatique.net/blog/2014/02/07/les-transports-public-suisses-finalement-sur-google-map/
 - [x] http://staging.antistatique.net/blog/2014/02/04/remote-le-travail-a-distance/
 - [x] http://staging.antistatique.net/blog/2014/02/13/eh-et-si-on-faisait-une-fete-dans-les-bureaux/
 - [x] http://staging.antistatique.net/blog/2014/03/12/coworking-space-et-travail-a-distance-du-massachusset-au-michigan/
 - [x] http://staging.antistatique.net/blog/2014/07/21/my-last-month-in-sardinia-work-and-fun/
 - [x] http://staging.antistatique.net/blog/2014/07/27/swissjeese-2014-javascript-suisse/
 - [x] http://staging.antistatique.net/blog/2014/08/18/magento-cycle-de-vie-client/
 - [x] http://staging.antistatique.net/blog/2014/08/22/the-firm/
 - [x] http://staging.antistatique.net/blog/2014/08/28/frontend-conference-a-zurich-2014/
 - [x] http://staging.antistatique.net/blog/2014/10/29/3094/
 - [x] http://staging.antistatique.net/blog/2015/02/17/ong-et-associations-ameliorer-les-dons-en-ligne/
 - [x] http://staging.antistatique.net/blog/2015/02/25/ong-et-associations-ameliorer-les-dons-en-ligne-part-2/
 - [x] http://staging.antistatique.net/blog/2015/03/25/athena-une-application-de-gestion-pour-les-federations-sportives/
 - [x] http://staging.antistatique.net/blog/2015/05/26/processus-de-realisation/
 - [x] http://staging.antistatique.net/blog/2015/05/22/la-dette-technique/
 - [x] http://staging.antistatique.net/blog/2015/05/28/expo-milano-2015-pavillon-suisse/
 - [x] http://staging.antistatique.net/blog/2015/06/01/experimentation-avec-node-js/

**Comment by gido** [comment]
@tonifisler @nsz @zufrieden I updated this ticket with missing blog post redirection. Maybe some of them don't exists anymore...

**Comment by gido** [comment]
When the mapping is ready, you need to insert new values into the MySQL table `migrate_blog_url` (Sequel can import CSV):

![screen shot 2015-06-12 at 14 10 07](https://cloud.githubusercontent.com/assets/101859/8129772/c4982bc8-110c-11e5-972d-508f0bb3e756.png)

**Comment by gido** [comment]
@zufrieden @dmrrlc This one is critical. Some of the url listed below is in the top 20 in Analytics.
