### ISSUE TITLE
Website: Configurer les URL Redirection

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#104]
Tous sauf le blog, see #103

Look for somethink like this in the `.htaccess`:

```
  Redirect /fr/team /fr/nous
  Redirect /fr/portfolio /fr/nous/travaillons
  # ...
```

## TODO
=== general ===
 - [ ] http://staging.antistatique.net/fr/job/web-developer-drupal

=== portfolio ===
 - [ ] http://staging.antistatique.net/fr/portfolio/devenez
 - [ ] http://staging.antistatique.net/fr/portfolio/prateo
 - [ ] http://staging.antistatique.net/fr/portfolio/cardis
 - [ ] http://staging.antistatique.net/fr/portfolio/brouillondeculture
 - [ ] http://staging.antistatique.net/fr/portfolio/rodondijoye
 - [ ] http://staging.antistatique.net/fr/portfolio/pierreetoile
 - [ ] http://staging.antistatique.net/fr/portfolio/billetlemillion
 - [ ] http://staging.antistatique.net/fr/portfolio/courtierspartenaires
 - [ ] http://staging.antistatique.net/fr/portfolio/ehl
 - [ ] http://staging.antistatique.net/fr/portfolio/electrosanne
 - [ ] http://staging.antistatique.net/fr/portfolio/faceit
 - [ ] http://staging.antistatique.net/fr/portfolio/urturn
 - [ ] http://staging.antistatique.net/fr/portfolio/tennislausanne
 - [ ] http://staging.antistatique.net/fr/portfolio/derham
 - [x] http://staging.antistatique.net/fr/portfolio/uchitomi
 - [ ] http://staging.antistatique.net/fr/portfolio/richter
 - [ ] http://staging.antistatique.net/fr/portfolio/tehran

=== blog ===
 - [x] http://staging.antistatique.net/blog/
 - [x] http://staging.antistatique.net/blog/author/gde/ (-> redirect to user page ?)
 - [x] http://staging.antistatique.net/blog/author/ludovic/
 - [x] http://staging.antistatique.net/blog/author/admin/
 - [x] http://staging.antistatique.net/blog/author/guillaume/
 - [x] http://staging.antistatique.net/blog/author/luc/
 - [x] http://staging.antistatique.net/blog/author/ludovic/
 - [x] http://staging.antistatique.net/blog/author/philippe/
 - [x] http://staging.antistatique.net/blog/author/saniha/
 - [x] http://staging.antistatique.net/blog/author/smi/
 - [ ] http://staging.antistatique.net/blog/author/nsz/
 - [ ] http://staging.antistatique.net/blog/author/agz/
 - [x] http://staging.antistatique.net/blog/author/toni/
 - [x] http://staging.antistatique.net/blog/author/ygn/

**Comment by gido** [comment]
@tonifisler @nsz @zufrieden I updated this ticket with missing redirection

**Comment by zufrieden** [comment]
- [ ] antistatique.net/blog/page/3
